"""
Comprehensive list of ALL tourism and historical sites in Jordan, organized by governorate.
Sources: Wikipedia archaeological sites, Jordan Tourism Board (visitjordan.com), UNESCO World Heritage, MoTA.
"""

TOURISM_SITES = [
    # ==========================================
    # AMMAN (Capital)
    # ==========================================
    {
        "name_en": "Amman Citadel (Jabal al-Qal'a)",
        "name_ar": "القلعة عمان",
        "site_type": "archaeological",
        "gov_code": "AMM",
        "lat": 31.9500,
        "lng": 35.9340,
        "era": "Neolithic-Roman-Umayyad",
        "description": "Major archaeological complex: Temple of Hercules, Umayyad Palace, Byzantine Basilica, Jordan Archaeological Museum",
    },
    {
        "name_en": "Roman Theatre (Amman)",
        "name_ar": "المسرح الروماني عمان",
        "site_type": "archaeological",
        "gov_code": "AMM",
        "lat": 31.9500,
        "lng": 35.9400,
        "era": "Roman (2nd century AD)",
        "description": "6,000-seat Roman amphitheatre, best-preserved in Jordan",
    },
    {
        "name_en": "Odeon Theatre (Amman)",
        "name_ar": "مسرح الأوديون عمان",
        "site_type": "archaeological",
        "gov_code": "AMM",
        "lat": 31.9497,
        "lng": 35.9397,
        "era": "Roman (2nd century AD)",
        "description": "Small Roman theatre, used for concerts and events",
    },
    {
        "name_en": "Nymphaeum (Amman)",
        "name_ar": "النيمفيوم عمان",
        "site_type": "archaeological",
        "gov_code": "AMM",
        "lat": 31.9510,
        "lng": 35.9380,
        "era": "Roman (2nd century AD)",
        "description": "Grand public fountain complex, once ornately decorated",
    },
    {
        "name_en": "King Hussein Mosque",
        "name_ar": "مسجد الملك حسين",
        "site_type": "religious",
        "gov_code": "AMM",
        "lat": 31.9510,
        "lng": 35.9360,
        "era": "Ottoman (rebuilt 1924)",
        "description": "Heart of modern downtown, rebuilt on ancient mosque site",
    },
    {
        "name_en": "King Abdullah I Mosque",
        "name_ar": "مسجد الملك عبدالله الأول",
        "site_type": "religious",
        "gov_code": "AMM",
        "lat": 31.9680,
        "lng": 35.9200,
        "era": "Modern (1989)",
        "description": "Major blue-domed mosque, Islamic museum inside",
    },
    {
        "name_en": "Ain Ghazal",
        "name_ar": "عين غزال",
        "site_type": "archaeological",
        "gov_code": "AMM",
        "lat": 31.9900,
        "lng": 35.9000,
        "era": "Neolithic (7250 BC)",
        "description": "One of the largest Neolithic sites in the Near East, plaster statues",
    },
    {
        "name_en": "Jordan Museum",
        "name_ar": "المتحف الأردني",
        "site_type": "museum",
        "gov_code": "AMM",
        "lat": 31.9480,
        "lng": 35.9300,
        "era": "Modern",
        "description": "National museum with Dead Sea Scrolls, Ain Ghazal statues",
    },
    {
        "name_en": "Royal Automobile Museum",
        "name_ar": "متحف السيارات الملكي",
        "site_type": "museum",
        "gov_code": "AMM",
        "lat": 31.9750,
        "lng": 35.8600,
        "era": "Modern",
        "description": "Classic car collection of the Royal Family",
    },
    {
        "name_en": "Rainbow Street",
        "name_ar": "شارع الرينبو",
        "site_type": "cultural",
        "gov_code": "AMM",
        "lat": 31.9530,
        "lng": 35.9220,
        "era": "Modern",
        "description": "Cultural street with galleries, cafes, souks",
    },
    {
        "name_en": "Rujm al-Malfouf",
        "name_ar": "رجم ملفوف",
        "site_type": "archaeological",
        "gov_code": "AMM",
        "lat": 31.9600,
        "lng": 35.9500,
        "era": "Bronze Age",
        "description": "Iron Age tower and megalithic tomb",
    },
    {
        "name_en": "Downtown Souks (Al-Balad)",
        "name_ar": "أسواق وسط البلد",
        "site_type": "cultural",
        "gov_code": "AMM",
        "lat": 31.9500,
        "lng": 35.9360,
        "era": "Ottoman-Modern",
        "description": "Traditional gold souk, spice market, and commercial district",
    },
    {
        "name_en": "Iraq al-Amir (Qasr al-Abd)",
        "name_ar": "عراق الأمير",
        "site_type": "archaeological",
        "gov_code": "AMM",
        "lat": 31.9100,
        "lng": 35.7300,
        "era": "Hellenistic (2nd century BC)",
        "description": "Palace of the Tobiad family, one of few Hellenistic buildings in Jordan",
    },
    # ==========================================
    # IRBID
    # ==========================================
    {
        "name_en": "Umm Qais (Gadara)",
        "name_ar": "أم قيس (غادارا)",
        "site_type": "archaeological",
        "gov_code": "IRB",
        "lat": 32.6528,
        "lng": 35.6811,
        "era": "Roman-Byzantine",
        "description": "Decapolis city with Roman streets, theatre, basilica; views of Sea of Galilee",
    },
    {
        "name_en": "Pella (Tabqet Fahl)",
        "name_ar": "بيلا",
        "site_type": "archaeological",
        "gov_code": "IRB",
        "lat": 32.4500,
        "lng": 35.6100,
        "era": "Neolithic-Umayyad",
        "description": "One of the oldest continuously inhabited cities, 6000 years of occupation",
    },
    {
        "name_en": "Capitolias (Beit Ras)",
        "name_ar": "بيت راس (كابيتوليس)",
        "site_type": "archaeological",
        "gov_code": "IRB",
        "lat": 32.5700,
        "lng": 35.8700,
        "era": "Roman",
        "description": "Decapolis city with theatre, tombs, and Roman road",
    },
    {
        "name_en": "Abila (Decapolis)",
        "name_ar": "أبيلا",
        "site_type": "archaeological",
        "gov_code": "IRB",
        "lat": 32.6700,
        "lng": 35.8700,
        "era": "Roman-Byzantine",
        "description": "Decapolis city with churches, tombs, underground cisterns",
    },
    {
        "name_en": "Tell Abu al-Kharaz",
        "name_ar": "تل أبو الخرز",
        "site_type": "archaeological",
        "gov_code": "IRB",
        "lat": 32.5200,
        "lng": 35.6000,
        "era": "Bronze Age-Iron Age",
        "description": "Major archaeological tell with 3000+ years of occupation",
    },
    {
        "name_en": "Tell el-Hammam",
        "name_ar": "تل الحمام",
        "site_type": "archaeological",
        "gov_code": "IRB",
        "lat": 31.8800,
        "lng": 35.6600,
        "era": "Bronze Age",
        "description": "Large Bronze Age city, possibly Biblical Sodom",
    },
    # ==========================================
    # JERASH
    # ==========================================
    {
        "name_en": "Jerash (Gerasa)",
        "name_ar": "جرش (جيراسا)",
        "site_type": "archaeological",
        "gov_code": "JER",
        "lat": 32.2806,
        "lng": 35.8994,
        "era": "Roman-Byzantine",
        "description": "Best-preserved Roman provincial city: Oval Plaza, Cardo, Theatre, Temple of Artemis, Hadrian's Arch",
    },
    {
        "name_en": "Hadrian's Arch (Jerash)",
        "name_ar": "بوابة هادريان جرش",
        "site_type": "archaeological",
        "gov_code": "JER",
        "lat": 32.2770,
        "lng": 35.8940,
        "era": "Roman (129 AD)",
        "description": "Triumphal arch built for Emperor Hadrian's visit",
    },
    {
        "name_en": "Temple of Artemis (Jerash)",
        "name_ar": "معبد أرتميس جرش",
        "site_type": "archaeological",
        "gov_code": "JER",
        "lat": 32.2810,
        "lng": 35.8970,
        "era": "Roman (150 AD)",
        "description": "Dedicated to patron goddess of Gerasa, massive Corinthian columns",
    },
    {
        "name_en": "South Theatre (Jerash)",
        "name_ar": "المسرح الجنوبي جرش",
        "site_type": "archaeological",
        "gov_code": "JER",
        "lat": 32.2780,
        "lng": 35.8980,
        "era": "Roman (90 AD)",
        "description": "3,000-seat theatre with remarkable acoustics",
    },
    {
        "name_en": "Church of Saints Cosmas and Damianos",
        "name_ar": "كنيسة القديسين قزمان ودميان",
        "site_type": "religious",
        "gov_code": "JER",
        "lat": 32.2830,
        "lng": 35.8980,
        "era": "Byzantine (6th century)",
        "description": "Beautiful Byzantine church mosaics",
    },
    # ==========================================
    # MAFAQ
    # ==========================================
    {
        "name_en": "Qasr Azraq",
        "name_ar": "قصر الأزرق",
        "site_type": "archaeological",
        "gov_code": "MAF",
        "lat": 31.8800,
        "lng": 36.8300,
        "era": "Roman-Ayyubid",
        "description": "Roman fortress used by Lawrence of Arabia, basalt construction",
    },
    {
        "name_en": "Umm el-Jimal",
        "name_ar": "أم الجمال",
        "site_type": "archaeological",
        "gov_code": "MAF",
        "lat": 32.3264,
        "lng": 36.3658,
        "era": "Nabataean-Umayyad",
        "description": "Black basalt city, UNESCO candidate, well-preserved Nabataean-Roman town",
    },
    {
        "name_en": "Qasr Burqu'",
        "name_ar": "قصر برقع",
        "site_type": "archaeological",
        "gov_code": "MAF",
        "lat": 32.5600,
        "lng": 37.1300,
        "era": "Roman-Umayyad",
        "description": "Desert castle near volcanic lake",
    },
    {
        "name_en": "Jawa",
        "name_ar": "جوا",
        "site_type": "archaeological",
        "gov_code": "MAF",
        "lat": 32.3300,
        "lng": 36.8300,
        "era": "Early Bronze Age",
        "description": "Earliest known dam-based irrigation settlement in the world",
    },
    # ==========================================
    # AJLOUN
    # ==========================================
    {
        "name_en": "Ajlun Castle (Qal'at ar-Rabadh)",
        "name_ar": "قلعة عجلون",
        "site_type": "archaeological",
        "gov_code": "AJL",
        "lat": 32.3325,
        "lng": 35.7517,
        "era": "Ayyubid (1184 AD)",
        "description": "Saladin's castle, built to counter Crusaders, panoramic views",
    },
    {
        "name_en": "Tell Mar Elias",
        "name_ar": "تل مار إلياس",
        "site_type": "religious",
        "gov_code": "AJL",
        "lat": 32.3600,
        "lng": 35.7200,
        "era": "Byzantine",
        "description": "Birthplace of Prophet Elijah, Byzantine church ruins with mosaics",
    },
    {
        "name_en": "Ajloun Forest Reserve",
        "name_ar": "محمية غابات عجلون",
        "site_type": "natural",
        "gov_code": "AJL",
        "lat": 32.3500,
        "lng": 35.7400,
        "era": "Natural",
        "description": "RSCN nature reserve, hiking trails through Mediterranean forest",
    },
    # ==========================================
    # BALQA
    # ==========================================
    {
        "name_en": "Al-Maghtas (Bethany Beyond the Jordan)",
        "name_ar": "المغطس",
        "site_type": "religious",
        "gov_code": "BAL",
        "lat": 31.8378,
        "lng": 35.5456,
        "era": "Byzantine-Roman",
        "description": "UNESCO World Heritage Site, baptism site of Jesus Christ",
    },
    {
        "name_en": "Dead Sea Beaches",
        "name_ar": "شواطئ البحر الميت",
        "site_type": "natural",
        "gov_code": "BAL",
        "lat": 31.7500,
        "lng": 35.5500,
        "era": "Natural",
        "description": "Lowest point on Earth (-430m), salt lake, therapeutic mud",
    },
    {
        "name_en": "Wadi Mujib (Siq Trail)",
        "name_ar": "وادي الموجب",
        "site_type": "natural",
        "gov_code": "BAL",
        "lat": 31.4600,
        "lng": 35.5700,
        "era": "Natural",
        "description": "Grand Canyon of Jordan, canyon hiking, water trails",
    },
    {
        "name_en": "Deir Alla",
        "name_ar": "دير علا",
        "site_type": "archaeological",
        "gov_code": "BAL",
        "lat": 32.1800,
        "lng": 35.6200,
        "era": "Bronze Age-Iron Age",
        "description": "Important archaeological tell with Balaam inscription",
    },
    {
        "name_en": "Lot's Cave (Zoar)",
        "name_ar": "مغارة لوط",
        "site_type": "religious",
        "gov_code": "BAL",
        "lat": 31.2700,
        "lng": 35.5500,
        "era": "Byzantine",
        "description": "Church built over cave where Lot sheltered, Byzantine mosaics",
    },
    {
        "name_en": "Wadi Shu'eib",
        "name_ar": "وادي شعيب",
        "site_type": "archaeological",
        "gov_code": "BAL",
        "lat": 32.0500,
        "lng": 35.7600,
        "era": "Bronze Age",
        "description": "Archaeological site with extensive Bronze Age occupation",
    },
    # ==========================================
    # ZARQA
    # ==========================================
    {
        "name_en": "Azraq Wetland Reserve",
        "name_ar": "محمية الأزرق المائية",
        "site_type": "natural",
        "gov_code": "ZAR",
        "lat": 31.8300,
        "lng": 36.8200,
        "era": "Natural",
        "description": "Desert oasis, bird migration stopover, RSCN reserve",
    },
    {
        "name_en": "Kharaneh IV",
        "name_ar": "خارنة الرابع",
        "site_type": "archaeological",
        "gov_code": "ZAR",
        "lat": 31.9000,
        "lng": 36.8000,
        "era": "Epipaleolithic",
        "description": "Important hunter-gatherer site, one of the oldest huts in the world",
    },
    # ==========================================
    # MADABA
    # ==========================================
    {
        "name_en": "Madaba Mosaic Map (St. George's Church)",
        "name_ar": "خريطة مادبا الفسيفسائية",
        "site_type": "religious",
        "gov_code": "MAD",
        "lat": 31.7167,
        "lng": 35.7967,
        "era": "Byzantine (6th century)",
        "description": "Oldest surviving cartographic depiction of the Holy Land",
    },
    {
        "name_en": "Mount Nebo",
        "name_ar": "جبل نيبو",
        "site_type": "religious",
        "gov_code": "MAD",
        "lat": 31.7690,
        "lng": 35.7270,
        "era": "Byzantine",
        "description": "Where Moses viewed the Promised Land, Moses Memorial Church with mosaics",
    },
    {
        "name_en": "Madaba Archaeological Park",
        "name_ar": "الحديقة الأثرية مادبا",
        "site_type": "archaeological",
        "gov_code": "MAD",
        "lat": 31.7170,
        "lng": 35.7960,
        "era": "Roman-Byzantine",
        "description": "Hippolytus Hall mosaics, Byzantine church ruins",
    },
    {
        "name_en": "Mukawir (Machaerus)",
        "name_ar": "مكاور (مكاور)",
        "site_type": "archaeological",
        "gov_code": "MAD",
        "lat": 31.5600,
        "lng": 35.6600,
        "era": "Roman-Herodian",
        "description": "Herod's fortress where John the Baptist was beheaded",
    },
    {
        "name_en": "Umm ar-Rasas (Kastrom Mefa'a)",
        "name_ar": "أم الرصاص",
        "site_type": "archaeological",
        "gov_code": "MAD",
        "lat": 31.4992,
        "lng": 35.9214,
        "era": "Roman-Umayyad",
        "description": "UNESCO World Heritage Site, extensive Byzantine mosaics",
    },
    {
        "name_en": "Shrine of the Prophet Lot (Nabi Lut)",
        "name_ar": "مقام النبي لوط",
        "site_type": "religious",
        "gov_code": "MAD",
        "lat": 31.7300,
        "lng": 35.7800,
        "era": "Islamic",
        "description": "Islamic shrine dedicated to Prophet Lot",
    },
    {
        "name_en": "Herodus Church (Madaba)",
        "name_ar": "كنيسة هيرودس مادبا",
        "site_type": "archaeological",
        "gov_code": "MAD",
        "lat": 31.7180,
        "lng": 35.7970,
        "era": "Byzantine",
        "description": "Byzantine church with well-preserved floor mosaics",
    },
    # ==========================================
    # KARAK
    # ==========================================
    {
        "name_en": "Karak Castle (Crusader Fortress)",
        "name_ar": "قلعة الكرك",
        "site_type": "archaeological",
        "gov_code": "KAR",
        "lat": 31.1853,
        "lng": 35.7047,
        "era": "Crusader-Ayyubid (1142 AD)",
        "description": "Largest Crusader castle in the Levantine, massive underground galleries",
    },
    {
        "name_en": "Bab ed-Dhra",
        "name_ar": "باب الذرا",
        "site_type": "archaeological",
        "gov_code": "KAR",
        "lat": 31.2300,
        "lng": 35.5300,
        "era": "Early Bronze Age",
        "description": "Possible site of Biblical Sodom, extensive cemetery",
    },
    {
        "name_en": "Ghor es-Safi",
        "name_ar": "غور الصافي",
        "site_type": "archaeological",
        "gov_code": "KAR",
        "lat": 31.0500,
        "lng": 35.4800,
        "era": "Bronze-Byzantine",
        "description": "Zoar/Biblical site, sugar factory ruins, lowest archaeological site on Earth",
    },
    {
        "name_en": "Wadi Mujib (Southern Section)",
        "name_ar": "وادي الموجب الجنوبي",
        "site_type": "natural",
        "gov_code": "KAR",
        "lat": 31.3500,
        "lng": 35.6200,
        "era": "Natural",
        "description": "Dramatic canyon, nature reserve, adventure trails",
    },
    {
        "name_en": "Karak Archaeological Museum",
        "name_ar": "متحف الكرك الأثري",
        "site_type": "museum",
        "gov_code": "KAR",
        "lat": 31.1850,
        "lng": 35.7050,
        "era": "Museum",
        "description": "Mamluke-era museum inside the castle complex",
    },
    # ==========================================
    # TAFILAH
    # ==========================================
    {
        "name_en": "Dana Nature Reserve",
        "name_ar": "محمية ضانا الطبيعية",
        "site_type": "natural",
        "gov_code": "TAF",
        "lat": 30.6400,
        "lng": 35.6200,
        "era": "Natural",
        "description": "RSCN reserve, 320 species of plants, 200 species of birds, hiking",
    },
    {
        "name_en": "Busaira (Biblical Bozrah)",
        "name_ar": "بوصيرا",
        "site_type": "archaeological",
        "gov_code": "TAF",
        "lat": 30.7600,
        "lng": 35.5900,
        "era": "Edomite-Roman",
        "description": "Capital of the Edomite kingdom, Biblical Bozrah",
    },
    {
        "name_en": "Gharandal",
        "name_ar": "غرندل",
        "site_type": "archaeological",
        "gov_code": "TAF",
        "lat": 30.5600,
        "lng": 35.5800,
        "era": "Roman-Byzantine",
        "description": "Roman fort and settlement on the Via Nova Traiana",
    },
    # ==========================================
    # MA'AN (includes Petra)
    # ==========================================
    {
        "name_en": "Petra (Al-Khazneh / Treasury)",
        "name_ar": "البتراء (الخزنة)",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3285,
        "lng": 35.4444,
        "era": "Nabataean (300 BC-100 AD)",
        "description": "UNESCO World Heritage, New7Wonders, rose-red Nabataean city",
    },
    {
        "name_en": "Petra - The Siq",
        "name_ar": "البتراء - السيق",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3240,
        "lng": 35.4500,
        "era": "Nabataean",
        "description": "1.2km narrow gorge entrance to Petra",
    },
    {
        "name_en": "Petra - The Monastery (Ad-Deir)",
        "name_ar": "البتراء - الدير",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3400,
        "lng": 35.4340,
        "era": "Nabataean (1st century BC)",
        "description": "Largest carved monument in Petra, 50m wide facade",
    },
    {
        "name_en": "Petra - Royal Tombs",
        "name_ar": "البتراء - المقابر الملكية",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3310,
        "lng": 35.4430,
        "era": "Nabataean",
        "description": "Urn Tomb, Silk Tomb, Corinthian Tomb, Palace Tomb",
    },
    {
        "name_en": "Petra - Theatre",
        "name_ar": "البتراء - المسرح",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3290,
        "lng": 35.4440,
        "era": "Nabataean-Roman",
        "description": "Carved from rock face, seats 4,000-8,500",
    },
    {
        "name_en": "Petra - High Place of Sacrifice",
        "name_ar": "البتراء - مرتفع الذبيحة",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3310,
        "lng": 35.4420,
        "era": "Nabataean",
        "description": "Altar platform at summit with panoramic views",
    },
    {
        "name_en": "Petra - Street of Facades",
        "name_ar": "البتراء - شارع الواجهات",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3280,
        "lng": 35.4440,
        "era": "Nabataean",
        "description": "Row of carved tomb facades along the main path",
    },
    {
        "name_en": "Petra Museum",
        "name_ar": "متحف البتراء",
        "site_type": "museum",
        "gov_code": "MAA",
        "lat": 30.3220,
        "lng": 35.4500,
        "era": "Modern",
        "description": "280 artifacts from the Petra region",
    },
    {
        "name_en": "Little Petra (Siq al-Barid)",
        "name_ar": "البتراء الصغيرة",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3800,
        "lng": 35.4600,
        "era": "Nabataean",
        "description": "Suburb of Petra with painted dining hall, triclinium",
    },
    {
        "name_en": "Shobak Castle (Montreal)",
        "name_ar": "قلعة الشوبك",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.5200,
        "lng": 35.5600,
        "era": "Crusader (1115 AD)",
        "description": "First Crusader castle in the Holy Land, built by Baldwin I",
    },
    {
        "name_en": "Humayma (Hawara)",
        "name_ar": "حميمة",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 29.9800,
        "lng": 35.3200,
        "era": "Nabataean-Roman-Abbasid",
        "description": "Nabataean waystation, birthplace of Abbasid dynasty",
    },
    {
        "name_en": "Udhruh",
        "name_ar": "أذرح",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.2800,
        "lng": 35.6200,
        "era": "Roman-Umayyad",
        "description": "Roman fortress on Via Nova Traiana, Umayyad caravanserai",
    },
    {
        "name_en": "Ba'ja",
        "name_ar": "بجا",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3400,
        "lng": 35.4400,
        "era": "Pre-Pottery Neolithic",
        "description": "Pre-Pottery Neolithic settlement near Petra",
    },
    {
        "name_en": "Basta",
        "name_ar": "بسطا",
        "site_type": "archaeological",
        "gov_code": "MAA",
        "lat": 30.3500,
        "lng": 35.4400,
        "era": "Pre-Pottery Neolithic",
        "description": "Neolithic site with early farming evidence",
    },
    # ==========================================
    # AQABA
    # ==========================================
    {
        "name_en": "Aqaba Marine Park",
        "name_ar": "منتزه العقبة البحري",
        "site_type": "coastal",
        "gov_code": "AQAB",
        "lat": 29.4000,
        "lng": 34.9800,
        "era": "Natural",
        "description": "Coral reef diving and snorkeling, Red Sea marine life",
    },
    {
        "name_en": "Aqaba Castle (Mamluk Fort)",
        "name_ar": "قلعة العقبة",
        "site_type": "archaeological",
        "gov_code": "AQAB",
        "lat": 29.5233,
        "lng": 35.0072,
        "era": "Mamluk-Crusader",
        "description": "14th century Mamluk fort, site of the Arab Revolt's first battle (1917)",
    },
    {
        "name_en": "Aqaba Church",
        "name_ar": "كنيسة العقبة",
        "site_type": "religious",
        "gov_code": "AQAB",
        "lat": 29.5260,
        "lng": 35.0060,
        "era": "4th century AD",
        "description": "Oldest known purpose-built church in the world (3rd-4th century)",
    },
    {
        "name_en": "Ayla (Islamic Aqaba)",
        "name_ar": "أيلة",
        "site_type": "archaeological",
        "gov_code": "AQAB",
        "lat": 29.5240,
        "lng": 35.0080,
        "era": "Early Islamic (7th century)",
        "description": "Ruins of the first Islamic city outside Arabian Peninsula",
    },
    {
        "name_en": "Wadi Rum (Valley of the Moon)",
        "name_ar": "وادي رم",
        "site_type": "natural",
        "gov_code": "AQAB",
        "lat": 29.5722,
        "lng": 35.4195,
        "era": "Natural/Nabataean",
        "description": "UNESCO World Heritage, Lawrence of Arabia, sandstone mountains, petroglyphs",
    },
    {
        "name_en": "Wadi Rum - Khazali Canyon",
        "name_ar": "وادي رم - وادي الخزالي",
        "site_type": "natural",
        "gov_code": "AQAB",
        "lat": 29.5600,
        "lng": 35.4300,
        "era": "Natural/Thamudic",
        "description": "Narrow canyon with ancient Thamudic inscriptions",
    },
    {
        "name_en": "Wadi Rum - Lawrence's Spring",
        "name_ar": "وادي رم - عين لورانس",
        "site_type": "natural",
        "gov_code": "AQAB",
        "lat": 29.5800,
        "lng": 35.4200,
        "era": "Natural",
        "description": "Natural spring associated with T.E. Lawrence",
    },
    {
        "name_en": "Wadi Rum - Burdah Rock Bridge",
        "name_ar": "وادي رم - جسر بردا",
        "site_type": "natural",
        "gov_code": "AQAB",
        "lat": 29.5600,
        "lng": 35.4100,
        "era": "Natural",
        "description": "Highest natural rock arch in Wadi Rum, 800m above desert",
    },
    {
        "name_en": "Wadi Rum - Um Fruth Rock Bridge",
        "name_ar": "وادي رم - جسر أم فروث",
        "site_type": "natural",
        "gov_code": "AQAB",
        "lat": 29.5500,
        "lng": 35.4200,
        "era": "Natural",
        "description": "Climbable natural rock bridge",
    },
    {
        "name_en": "Wadi Rum - Jabal Umm ad-Dami",
        "name_ar": "وادي رم - جبل أم الدامي",
        "site_type": "natural",
        "gov_code": "AQAB",
        "lat": 29.3500,
        "lng": 35.4300,
        "era": "Natural",
        "description": "Highest mountain in Jordan (1,854m), views of Saudi Arabia",
    },
    {
        "name_en": "Aqaba Marine Science Park",
        "name_ar": "منتزه علوم البحار العقبة",
        "site_type": "museum",
        "gov_code": "AQAB",
        "lat": 29.4200,
        "lng": 34.9800,
        "era": "Modern",
        "description": "Aquarium and marine education center",
    },
    {
        "name_en": "Aqaba Flagpole (Arab Revolt Plaza)",
        "name_ar": "ساحة الثورة العربية العقبة",
        "site_type": "cultural",
        "gov_code": "AQAB",
        "lat": 29.5230,
        "lng": 35.0070,
        "era": "Modern",
        "description": "Massive flagpole commemorating the Arab Revolt of 1917",
    },
]

TOTAL_SITES = len(TOURISM_SITES)
